version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
      - MSSQL_USER=${MSSQL_USER}
      - MSSQL_DATABASE=${MSSQL_DATABASE}
      - MSSQL_PID=${MSSQL_PID}
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    volumes:
      - sqlserverdata:/var/opt/mssql
    restart: always

volumes:
  sqlserverdata:
